source 'https://rubygems.org'

gem 'rails', '3.2.10'
gem 'bootstrap-sass', '2.1'
gem 'bcrypt-ruby', '3.0.1'
gem 'will_paginate', '3.0.3'
gem 'bootstrap-will_paginate', '0.0.6'
gem 'jquery-rails', '2.0.2'
gem 'rack', '1.4.1'
gem 'execjs'
gem 'activerecord-jdbc-adapter', '1.2.2.1'
gem 'therubyrhino'

group :development, :test do
  gem 'jdbc-sqlite3'
  gem 'activerecord-jdbcsqlite3-adapter'
  gem 'jruby-openssl'
  gem 'warbler'
  gem 'jruby-rack', '1.1.7'
  gem 'jdbc-maxdb'
  gem 'activerecord-maxdb-adapter'
  gem 'rspec-rails', '2.11.0'
  gem 'guard-rspec', '1.2.1'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '3.2.5'
  gem 'coffee-rails', '3.2.2'
  gem 'uglifier', '1.2.3'
end

group :test do
  gem 'capybara', '1.1.2'
  gem 'factory_girl_rails', '4.1.0'
  gem 'cucumber-rails', '1.2.1', :require => false
  gem 'database_cleaner', '0.7.0'
end

group :production do  
  gem 'jruby-openssl'
  gem 'jdbc-maxdb'
  gem 'activerecord-maxdb-adapter'
  gem 'activerecord-jdbc-adapter', '1.2.2.1'
  gem 'execjs' 
  gem 'therubyrhino'
end